---
title: "Useful Summary Tables"
output: html_document
---


```{css, echo = FALSE}
h1, .h1, h2, .h2, h3, .h3 {
    margin-top: 84px;
}
```

### Symbols

```{r, message=FALSE, warning=FALSE, echo = FALSE}
library(knitr)
library(kableExtra)
symbols <- data.frame(Response = c("quantitative", "categorical",
                                   "quantitative", "categorical",
                                   "quantitative"),
                         Explanatory = c("-", "-",
                                         "categorical",
                                         "categorical",
                                         "quantitative"),
                         Numerical_Quantity = c("mean", 
                                                "proportion",
                                                "difference in means",
                                                "difference in proportions",
                                                "correlation"),
                         Parameter = c("$\\mu$", "$p$", 
                                       "$\\mu_1 - \\mu_2$",
                                       "$p_1 - p_2$",
                                       "$\\rho$"),
                                       Statistic = c("$\\bar{x}$",
                                                     "$\\hat{p}$",
                                                     "$\\bar{x}_1 - \\bar{x}_2$",
                                                     "$\\hat{p}_1 - \\hat{p}_2$",
                                                     "$r$"))

symbols %>% 
  kable()  %>%
  kable_styling(bootstrap_options = c("responsive", "bordered")) 

```


### Common Test Statistics and Approximate Distributions


```{r, message=FALSE, warning=FALSE, echo = FALSE}
library(knitr)
library(kableExtra)
dists <- data.frame(Response = c("quantitative", "categorical",
                                   "quantitative", "categorical",
                                   "quantitative"),
                         Explanatory = c("-", "-",
                                         "categorical",
                                         "categorical",
                                         "quantitative"),
                         Numerical_Quantity = c("mean", 
                                                "proportion",
                                                "difference in means",
                                                "difference in proportions",
                                                "correlation"),
                         Test_Statistic = c("$\\frac{\\bar{x} - \\mu_o}{s/\\sqrt{n}}$",
                                            "$\\frac{\\hat{p} - p_o}{\\sqrt{\\frac{\\hat{p}(1 - \\hat{p})}{n}}}$",
                                            "$\\frac{\\bar{x}_1 - \\bar{x}_2 - 0}{\\sqrt{\\frac{s^2_1}{n_1} + \\frac{s^2_2}{n_2}}}$",
                                            "$\\frac{\\hat{p}_1 - \\hat{p}_2 - 0}{\\sqrt{\\frac{\\hat{p}(1 - \\hat{p})}{n_1} + \\frac{\\hat{p}(1 - \\hat{p})}{n_2}}}$",
                                            "$\\frac{r - 0}{\\sqrt{\\frac{1 - r^2}{n - 2}}}$"),
                    Distribution = c("$t(df = n - 1)$", "$N(0, 1)$", "$t(df = \\min(n_1, n_2) - 1)$",
                                     "$N(0, 1)$", "$t(df = n - 2)$"),
                    Assumptions = c("$n \\geq 30$ or data are normal",
                                  "Ten successes, Ten failures",
                                  "$n_1, n_2 \\geq 30$ or data are normal",
                                  "Ten successes, Ten failures in each category",
                                  "$n \\geq 30$ or data are normal"))

dists %>% 
  kable()  %>%
  kable_styling(bootstrap_options = c("responsive", "bordered")) 

```

### Common Distribution-Based Confidence Interval Formulae


```{r, message=FALSE, warning=FALSE, echo = FALSE}
library(knitr)
library(kableExtra)
cis <- data.frame(Response = c("quantitative", "categorical",
                                   "quantitative", "categorical",
                                   "quantitative"),
                         Explanatory = c("-", "-",
                                         "categorical",
                                         "categorical",
                                         "quantitative"),
                         Numerical_Quantity = c("mean", 
                                                "proportion",
                                                "difference in means",
                                                "difference in proportions",
                                                "correlation"),
                         Confidence_Interval = c("$\\bar{x} \\pm t^*s/\\sqrt{n}$",
                                            "$\\hat{p} \\pm z^* \\sqrt{\\frac{\\hat{p}(1 - \\hat{p})}{n}}$",
                                            "$\\bar{x}_1 - \\bar{x}_2 \\pm t^* \\sqrt{\\frac{s^2_1}{n_1} + \\frac{s^2_2}{n_2}}$",
                                            "$\\hat{p}_1 - \\hat{p}_2 \\pm z^* \\sqrt{\\frac{\\hat{p}_1(1 - \\hat{p}_1)}{n_1} + \\frac{\\hat{p}_2(1 - \\hat{p}_2)}{n_2}}$",
                                            "$r \\pm t^* \\sqrt{\\frac{1 - r^2}{n - 2}}$"),
                    Distribution = c("$t(df = n - 1)$", "$N(0, 1)$", "$t(df = \\min(n_1, n_2) - 1)$",
                                     "$N(0, 1)$", "$t(df = n - 2)$"),
                  Assumptions = c("$n \\geq 30$ or data are normal",
                                  "Ten successes, Ten failures",
                                  "$n_1, n_2 \\geq 30$ or data are normal",
                                  "Ten successes, Ten failures in each category",
                                  "$n \\geq 30$ or data are normal"))

cis %>% 
  kable()  %>%
  kable_styling(bootstrap_options = c("responsive", "bordered")) 

```

